export default {
  en: [
    { key: 'propositional logic', value: 'propositional logic' },
    { key: 'predicate logic', value: 'predicate logic' },
    { key: 'set theory', value: 'set theory' },
    { key: 'graph theory', value: 'graph theory' },
    { key: 'combinatorics', value: 'combinatorics' },
    { key: 'number theory', value: 'number theory' },
    { key: 'boolean algebra', value: 'boolean algebra' },
    { key: 'formal languages', value: 'formal languages' },
    { key: 'finite automata', value: 'finite automata' },
    { key: 'recurrence relations', value: 'recurrence relations' },
    { key: 'tree structures', value: 'tree structures' },
    { key: 'algorithm analysis', value: 'algorithm analysis' },
    { key: 'combinatorial optimization', value: 'combinatorial optimization' },
    { key: 'discrete structures', value: 'discrete structures' },
    { key: 'logic circuits', value: 'logic circuits' },
    { key: 'proof techniques', value: 'proof techniques' },
    { key: 'cryptographic protocols', value: 'cryptographic protocols' },
    { key: 'game theory', value: 'game theory' },
    { key: 'information theory', value: 'information theory' },
    { key: 'linear algebra', value: 'linear algebra' },
    { key: 'matroid theory', value: 'matroid theory' },
    { key: 'network flows', value: 'network flows' },
    { key: 'poset theory', value: 'poset theory' },
    { key: 'queueing theory', value: 'queueing theory' },
    { key: 'group theory', value: 'group theory' },
    { key: 'ring theory', value: 'ring theory' },
    { key: 'field theory', value: 'field theory' },
    { key: 'lattice theory', value: 'lattice theory' },
    { key: 'modal logic', value: 'modal logic' },
    { key: 'topology', value: 'topology' },
    { key: 'computability theory', value: 'computability theory' },
    { key: 'lambda calculus', value: 'lambda calculus' },
    { key: 'category theory', value: 'category theory' },
    { key: 'probability theory', value: 'probability theory' },
    { key: 'finite model theory', value: 'finite model theory' },
    { key: 'hypergraph theory', value: 'hypergraph theory' },
    { key: 'ramsey theory', value: 'ramsey theory' },
    { key: 'turing machines', value: 'turing machines' },
    { key: 'graph algorithms', value: 'graph algorithms' },
    { key: 'discrete optimization', value: 'discrete optimization' },
    { key: 'enumerative combinatorics', value: 'enumerative combinatorics' },
    { key: 'formal methods', value: 'formal methods' },
    { key: 'information retrieval', value: 'information retrieval' },
    { key: 'coding theory', value: 'coding theory' },
    { key: 'design theory', value: 'design theory' },
    { key: 'combinatorial geometry', value: 'combinatorial geometry' },
    { key: 'universal algebra', value: 'universal algebra' },
    { key: 'mathematical logic', value: 'mathematical logic' },
    { key: 'arithmetical logic', value: 'arithmetical logic' },
    { key: 'structural induction', value: 'structural induction' },
  ],
  ua: [
    { key: 'пропозиційна логіка', value: 'propositional logic' },
    { key: 'логіка предикатів', value: 'predicate logic' },
    { key: 'теорія множин', value: 'set theory' },
    { key: 'теорія графів', value: 'graph theory' },
    { key: 'комбінаторика', value: 'combinatorics' },
    { key: 'теорія чисел', value: 'number theory' },
    { key: 'булева алгебра', value: 'boolean algebra' },
    { key: 'формальні мови', value: 'formal languages' },
    { key: 'кінцеві автомати', value: 'finite automata' },
    { key: 'рекурентні відношення', value: 'recurrence relations' },
    { key: 'структури дерева', value: 'tree structures' },
    { key: 'аналіз алгоритмів', value: 'algorithm analysis' },
    { key: 'комбінаторна оптимізація', value: 'combinatorial optimization' },
    { key: 'дискретні структури', value: 'discrete structures' },
    { key: 'логічні схеми', value: 'logic circuits' },
    { key: 'техніки доведення', value: 'proof techniques' },
    { key: 'криптографічні протоколи', value: 'cryptographic protocols' },
    { key: 'теорія ігор', value: 'game theory' },
    { key: 'теорія інформації', value: 'information theory' },
    { key: 'лінійна алгебра', value: 'linear algebra' },
    { key: 'теорія матроїдів', value: 'matroid theory' },
    { key: 'теорія потоків в мережах', value: 'network flows' },
    { key: 'теорія часткових порядків', value: 'poset theory' },
    { key: 'теорія черг', value: 'queueing theory' },
    { key: 'теорія груп', value: 'group theory' },
    { key: 'теорія кілець', value: 'ring theory' },
    { key: 'теорія полів', value: 'field theory' },
    { key: 'теорія решіток', value: 'lattice theory' },
    { key: 'модальна логіка', value: 'modal logic' },
    { key: 'топологія', value: 'topology' },
    { key: 'теорія обчислювальності', value: 'computability theory' },
    { key: 'лямбда-числення', value: 'lambda calculus' },
    { key: 'теорія категорій', value: 'category theory' },
    { key: 'теорія ймовірностей', value: 'probability theory' },
    { key: 'теорія скінчених моделей', value: 'finite model theory' },
    { key: 'теорія гіперграфів', value: 'hypergraph theory' },
    { key: 'теорія Рамсея', value: 'ramsey theory' },
    { key: 'машини Тьюрінга', value: 'turing machines' },
    { key: 'алгоритми на графах', value: 'graph algorithms' },
    { key: 'дискретна оптимізація', value: 'discrete optimization' },
    { key: 'перелічувальна комбінаторика', value: 'enumerative combinatorics' },
    { key: 'формальні методи', value: 'formal methods' },
    { key: 'пошук інформації', value: 'information retrieval' },
    { key: 'теорія кодування', value: 'coding theory' },
    { key: 'теорія дизайну', value: 'design theory' },
    { key: 'комбінаторна геометрія', value: 'combinatorial geometry' },
    { key: 'універсальна алгебра', value: 'universal algebra' },
    { key: 'математична логіка', value: 'mathematical logic' },
    { key: 'арифметична логіка', value: 'arithmetical logic' },
    { key: 'структурна індукція', value: 'structural induction' },
  ],
};
